####################################################################
# VSTS Build Configuration, Version 1.3
#
# (c)2020 superdev GmbH
####################################################################

name: 3.0.$(date:yy)$(DayOfYear).$(rev:rr)
  
pool:
  vmImage: 'windows-2019'

trigger:
  branches:
    include:
    - master
    - develop
    - feature/*
    - bugfix/*
  paths:
    exclude:
    - README.md

variables:
  solution: 'EFCore.Toolkit.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: bleddynrichards.Assembly-Info-Task.Assembly-Info-NetCore.Assembly-Info-NetCore@2
  displayName: 'Set Assembly Manifest Data'
  inputs:
    FileNames: |
     EFCore.Toolkit.csproj
     EFCore.Toolkit.Abstractions.csproj
    InsertAttributes: true
    Product: 'EFCore.Toolkit'
    Description: ''
    Company: 'superdev GmbH'
    Copyright: '(c) $(date:YYYY) superdev GmbH'
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5.5.1'
  inputs:
    versionSpec: 5.5.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'

- powershell: |
   Write-Host "##vso[task.setvariable variable=PackageVersion]$(Build.BuildNumber)"
   Write-Host "##vso[task.setvariable variable=PackageVersionPre]$(Build.BuildNumber)$(BuildVersionPostfix)"
  displayName: 'Set PackageVersion'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(Parameters.solution)'
    msbuildArgs: ''
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

#- task: DotNetCoreCLI@2
#  displayName: 'Run UnitTests'
#  continueOnError: true # TODO: Activate test step
#  inputs:
#    command: test
#    projects: '**/*.Tests.csproj'
#    arguments: ''

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet PreRelease'
  inputs:
    command: pack
    packagesToPack: '**\EFCore.Toolkit*.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: PackageVersionPre

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet Prod'
  inputs:
    command: pack
    packagesToPack: '**\EFCore.Toolkit*.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: PackageVersion

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'

    Contents: |
     **\bin\$(BuildConfiguration)\**
     **\bin\*.nupkg

    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
