<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
		<OutputType>Library</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<IsPackable>true</IsPackable>
	</PropertyGroup>

	<!--NuGet package-->
	<PropertyGroup>
		<Product>EFCore.Toolkit.Abstractions</Product>
		<Description>EFCore.Toolkit.Abstractions contains data contracts used in EFCore.Toolkit.</Description>
		<Version>1.0.0</Version>
		<Authors>Thomas Galliker</Authors>
		<PackageId>EFCore.Toolkit.Abstractions</PackageId>
		<PackageTags>EntityFrameworkCore;Entity;Framework;Core;EFCore;EF;Core;Bulk;Batch;Extensions;Insert;Update;Delete;Read</PackageTags>
		<PackageIcon>logo.png</PackageIcon>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageProjectUrl>https://github.com/thomasgalliker/EFCore.Toolkit</PackageProjectUrl>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/thomasgalliker/EFCore.Toolkit</RepositoryUrl>
		<Company>superdev GmbH</Company>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<Copyright>Copyright $([System.DateTime]::Now.ToString(`yyyy`)) © Thomas Galliker</Copyright>
		<PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/../ReleaseNotes.txt"))</PackageReleaseNotes>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<EmbedAllSources>true</EmbedAllSources>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="True" PackagePath="\" />
		<None Include="..\LICENSE" Pack="True" PackagePath="\" />
		<None Include="..\logo.png" Pack="True" PackagePath="\" />
	</ItemGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>
</Project>
